var jogadores = [ {
    nome : "Gabigol",
    foto: 'https://www.ofutebolero.com.br/__export/1664162700318/sites/elfutboleromx/img/2022/09/25/gabigol-flamengo-1.png_1879290159.png',
    atacante: true,
    brasileiro: true,
    ano2019: true,
    copa_america:true,
    santos: true,
    cruzeiro: false,
    copa_do_mundo: false,
    zagueiro: false,
    olimpiadas: true,
    libertadores: false,
    gremio: false,
    champions: false,
    atletico_madri: true,
    pontos: 0,
    fluminense: false,
    perguntas: [["Já jogou no santos","santos"], ["Já ganhou a olímpiadas?","olimpiadas"]],
     },
     {
        nome : "Bruno Henrique",
        foto: "https://conteudo.imguol.com.br/c/esporte/fa/2022/06/06/bruno-henrique-gesticula-durante-jogo-do-flamengo-contra-o-botafogo-1654552598949_v2_450x600.jpg.webp",
        atacante: true,
        brasileiro: true,
        ano2019: true,
        copa_america:false,
        santos: true,
        cruzeiro: false,
        copa_do_mundo: false,
        zagueiro: false,
        olimpiadas: false,
        libertadores: false,
        gremio: false,
        champions: false,
        atletico_madri: true,
        pontos: 0,
        fluminense: false,
        perguntas: [["Já jogou no santos","santos"]],
        }, 
        {
            nome : "Everton Ribeiro",
            foto: "https://www.flaresenha.com/wp-content/uploads/2022/10/everton-ribeiro.jpg",
            atacante: false,
            brasileiro: true,
            ano2019: true,
            copa_america:true,
            santos: false,
            cruzeiro: true,
            copa_do_mundo: false,
            zagueiro: false,
            olimpiadas: false,
            libertadores: false,
            gremio: false,
            champions: false,
            atletico_madri: true,
            pontos: 0,
            fluminense: false,
            perguntas: [["Já jogou no cruzeiro?","cruzeiro"]],
    },{
        nome : "Everton Cebolinha",
        foto: "https://i.superesportes.com.br/mj0jvv16V51d-M4q3I4DAag8MOU=/650x0/smart/imgsapp.mg.superesportes.com.br/app/noticia_126420360808/2022/06/20/3971823/everton-cebolinha-ressalta-desejo-realizado-de-vestir-a-camisa-do-flamengo_1_61839.jpg",
        atacante: true,
        brasileiro: true,
        ano2019: false,
        copa_america: true,
        santos: false,
        cruzeiro: false,
        copa_do_mundo: false,
        zagueiro: false,
        olimpiadas: false,
        libertadores: true,
        gremio: true,
        champions: false,
        pontos:0,
        atletico_madri: true,
        fluminense: false,
        perguntas: [["Já jogou no grêmio?","gremio"],["Já ganhou a libertadores por outro clube sem ser o Flamengo?","libertadores"]],
     },{
        nome : "Felipe Luis",
        foto: "https://tntsports.com.br/__export/1610493925762/sites/esporteinterativo/img/2021/01/12/agif21010623271116_1_crop1610493924808.jpg_135829838.jpg",
        atacante: false,
        brasileiro: true,
        ano2019: true,
        copa_america: false,
        santos: false,
        cruzeiro: false,
        copa_do_mundo: true,
        zagueiro: false,
        olimpiadas: false,
        libertadores: false,
        gremio: false,
        champions: false,
        atletico_madri: true,
        pontos:0,
        fluminense: false,
        perguntas: [["Já jogou copa do mundo?","copa_do_mundo"], ['já jogou no atlético de madrid?',"atletico_madri"]],
     },{
        nome : "David Luis",
        foto: 'https://www.ofutebolero.com.br/__export/1647885739571/sites/elfutboleromx/img/2022/03/21/david_luiz_flamengo_5-23154136.jpg_1720385577.jpg',
        atacante: false,
        brasileiro: true,
        ano2019: false,
        copa_america: false,
        santos: false,
        cruzeiro: false,
        copa_do_mundo: true,
        zagueiro: true,
        olimpiadas: false,
        libertadores: false,
        gremio: false,
        champions: true,
        atletico_madri: false,
        pontos:0,
        fluminense: false,
        perguntas: [["Já jogou copa do mundo?","copa_do_mundo"], ['já foi campeão da champions league?',"champions"]],
     },
     {
        nome : "Rodrigo Caio",
        foto: 'https://a.espncdn.com/combiner/i?img=/photo/2022/0108/r959180_1296x729_16-9.jpg',
        atacante: false,
        brasileiro: true,
        ano2019: true,
        copa_america: false,
        santos: false,
        cruzeiro: false,
        copa_do_mundo: false,
        zagueiro: true,
        olimpiadas: true,
        libertadores: false,
        gremio: false,
        champions: true,
        atletico_madri: false,
        pontos:0,
        fluminense: false,
        perguntas: [["É zagueiro ?",'zagueiro'], ["Já ganhou a olímpiadas?","olimpiadas"]],
     },{
        nome : "Pedro",
        foto: "https://cms.somosfanaticos.com/__export/1659440338193/sites/fanaticos/img/2022/08/02/txcnico_pedex_e_clube_europeu_prepara_investida_pelo_atacante_pedrox_do_flamengo.jpg_242310155.jpg",
        atacante: true,
        brasileiro: true,
        ano2019: false,
        copa_america: false,
        santos: false,
        cruzeiro: false,
        copa_do_mundo: false,
        zagueiro: false,
        olimpiadas: false,
        libertadores: false,
        gremio: false,
        champions: true,
        atletico_madri: false,
        pontos:0,
        fluminense: true,
        perguntas: [['Já jogou no Fluminense?', 'fluminense']],
     },{
        nome : "Arrascaeta",
        foto: "https://conteudo.imguol.com.br/c/esporte/30/2022/08/02/arrascaeta-comemora-gol-do-flamengo-sobre-o-corinthians-pela-libertadores-1659489351819_v2_3x4.jpg",
        atacante: false,
        brasileiro: false,
        ano2019: true,
        copa_america: true,
        santos: false,
        cruzeiro: true,
        copa_do_mundo: false,
        zagueiro: false,
        olimpiadas: false,
        libertadores: false,
        gremio: false,
        champions: false,
        atletico_madri: false,
        pontos:0,
        fluminense: false,
        perguntas: [["Já jogou no cruzeiro?","cruzeiro"]],
     }    
]


const perguntas_iniciais = [
    ["É atacante ?",'atacante'],
    ["É brasileiro ?",'brasileiro'],
    ["Está no flamengo desde 2019 ?",'ano2019'],
    ["Jogou a última copa anérica ?",'copa_america']
]


let lista = [{nome: 'Gabigol', pontos:0},{nome:"Bruno Henrique", pontos: 0}, {nome: "Arrascaeta", pontos:0}, {nome: "Everton Ribeiro", pontos:0}];


var atributos = ['atacante', 'brasileiro','ano2019', 'copa_america'];